[package]
name = "raytracing-series-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = { version = "^0.29.0", features = [
    "x11",
    "rwh_04",
    "rwh_05",
    "rwh_06",
    "wayland",
] }
derive_more = "^0.99.17"
glam = { version = "^0.28.0", features = ["rand"] }
indicatif = { version = "^0.17.6", features = ["rayon"] }
itertools = "^0.11.0"
no_deadlocks = "1.3.1"
rand = { version = "^0.8.5", features = [
    "std",
    "std_rng",
    "getrandom",
    "small_rng",
] }
rayon = "^1.8.0"
wgpu = "0.16.0"
lazy_static = "^1.5.0"
pixels = "^0.13.0"
winit_input_helper = "^0.16"
[profile.release]
incremental = true
lto = "fat"
dhat-on = []
